### ISSUE TITLE
Trying to add Bitbucket vcs creds w/o a callback URL - SIGSEGV

### ISSUE THREAD

**Issue by tjtelan** [level11consulting/orbitalci#170]
I'm trying to add vcs creds, and I didn't want to add a callback URL, bc I'm just working with Vagrant. I don't need callbacks.

We're also exposing some secrets in these logs. We should probably take that out of log level `error`

```
{"error":"oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error_description\": \"No callback uri defined for the OAuth client.\", \"error\": \"invalid_request\"}","function":"github.com/shankj3/go-til/net.(*OAuthClient).Setup","level":"error","msg":"Unable to retrieve token for <redacted> at https://bitbucket.org/site/oauth2/access_token","time":"2018-12-13T23:46:09Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x71a832]

goroutine 127 [running]:
net/http.(*Client).deadline(0x0, 0xc00000e288, 0xf8, 0xc0004d8000)
        /snap/go/3039/src/net/http/client.go:187 +0x22
net/http.(*Client).do(0x0, 0xc0004d8000, 0x0, 0x0, 0x0)
        /snap/go/3039/src/net/http/client.go:527 +0xab
net/http.(*Client).Do(0x0, 0xc0004d8000, 0xc000150840, 0x32, 0x0)
        /snap/go/3039/src/net/http/client.go:509 +0x35
net/http.(*Client).Get(0x0, 0xc000150840, 0x32, 0xc000232000, 0x9, 0x435fcf)
        /snap/go/3039/src/net/http/client.go:398 +0x9d
github.com/shankj3/go-til/net.(*OAuthClient).GetUrl(0xc0002e3f20, 0xc000150840, 0x32, 0xfdb120, 0xc0002a2720, 0x0, 0x0)
        /home/vagrant/go/pkg/mod/github.com/shankj3/go-til@v0.4.3/net/net.go:120 +0x6b
github.com/level11consulting/ocelot/common/remote/bitbucket.(*Bitbucket).recurseOverRepos(0xc00020c090, 0xc000150840, 0x32, 0x1, 0x1)
        /home/vagrant/go/src/github.com/level11consulting/ocelot/common/remote/bitbucket/bitbucket.go:296 +0xa5
github.com/level11consulting/ocelot/common/remote/bitbucket.(*Bitbucket).Walk(0xc00020c090, 0x0, 0x0)
        /home/vagrant/go/src/github.com/level11consulting/ocelot/common/remote/bitbucket/bitbucket.go:89 +0xe4
created by github.com/level11consulting/ocelot/router/admin.SetupCredentials
        /home/vagrant/go/src/github.com/level11consulting/ocelot/router/admin/util.go:30 +0x25d
```

**Comment by shankj3** [comment]
This should be irrelevant, since the github code took out the URL as an option, since they don't change for vcs types

**Comment by tjtelan** [comment]
Closing bc github code isn't being used in production right now
